# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a739d8e0df395266dad3cd1ed9fcc10f2e612d5d51b5b65b8b428b9549fa38a23ace628568d7a18f2ff092ab60ea4722e425b58a9003ccb631df28c84e92004

test:
  secret_key_base: 6067463ccc1e7d29ddf7ee5db33a2cf9b7168d2cebaad36bccf4fbdb53c4a40370b42036e16587c61cfe2d6022958851d06543d25907bf1f2150416a7e37ce35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
